name: LiquidRhymes 
markdown: redcarpet
pygments: true
baseurl: /

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about.html
  - title: LiquidRhymes
    url: /liquidrhymes.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true

